language: ruby

before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - yarn

rvm:
  - 2.3.3

install:
  - bundle install --path vendor/bundle
  - yarn
  - bower install

script: bundle exec middleman build
